export const mockCourses = [
  {
    id: '1',
    title: 'Texas Hold\'em Mastery',
    slug: 'texas-holdem-mastery',
    instructor_name: 'Daniel Negreanu',
    price: 99,
    level: 'Intermediate',
    category: 'Cash Games',
    badge: 'bestseller',
    short_description: 'Master the fundamentals of Texas Hold\'em and dominate your opponents at any stakes.',
    full_description: 'Learn the core strategies that professional poker players use to consistently win at Texas Hold\'em. This comprehensive course covers hand selection, position strategy, pot odds, and advanced betting tactics.',
    thumbnail: '/courses/course-1.jpg',
  },
  {
    id: '2',
    title: 'Advanced Tournament Strategy',
    slug: 'advanced-tournament-strategy',
    instructor_name: 'Phil Ivey',
    price: 149,
    level: 'Advanced',
    category: 'Tournaments',
    badge: 'featured',
    short_description: 'Elevate your tournament game with strategies from one of the greatest poker minds.',
    full_description: 'Discover the advanced concepts that separate tournament champions from average players. Learn bubble strategy, ICM calculations, final table dynamics, and tournament-specific betting patterns.',
    thumbnail: '/courses/course-2.jpg',
  },
  {
    id: '3',
    title: 'Bankroll Management 101',
    slug: 'bankroll-management-101',
    instructor_name: 'Alex Fitzgerald',
    price: 49,
    level: 'Beginner',
    category: 'Fundamentals',
    short_description: 'Protect your poker bankroll and build sustainable profits with proven money management techniques.',
    full_description: 'Learn the critical skill of bankroll management that separates profitable players from broke ones. This course teaches stake selection, variance management, and risk assessment.',
    thumbnail: '/courses/course-3.jpg',
  },
  {
    id: '4',
    title: 'Position-Based Poker Strategy',
    slug: 'position-based-poker-strategy',
    instructor_name: 'Vanessa Selbst',
    price: 89,
    level: 'Intermediate',
    category: 'Cash Games',
    short_description: 'Master positional awareness to make better decisions and win more pots.',
    full_description: 'Position is power in poker. Learn how to exploit positional advantage, adjust your strategy based on your seat, and control the table dynamics from any position.',
    thumbnail: '/courses/course-4.jpg',
  },
  {
    id: '5',
    title: 'Psychology of Winning Poker',
    slug: 'psychology-winning-poker',
    instructor_name: 'Jared Tendler',
    price: 79,
    level: 'Beginner',
    category: 'Fundamentals',
    short_description: 'Develop the mental game and emotional control needed to perform at your highest level.',
    full_description: 'Master the psychological aspects of poker. Learn tilt management, decision-making under pressure, and how to maintain peak performance during long sessions.',
    thumbnail: '/courses/course-5.jpg',
  },
  {
    id: '6',
    title: 'Live Poker Tells & Reads',
    slug: 'live-poker-tells-reads',
    instructor_name: 'Mike Postle',
    price: 109,
    level: 'Intermediate',
    category: 'Live Poker',
    short_description: 'Learn to read your opponents like a book and extract maximum value from live games.',
    full_description: 'Discover the physical and behavioral tells that reveal your opponents\' hand strength. Learn how to exploit these tells and protect yourself against being read.',
    thumbnail: '/courses/course-6.jpg',
  },
  {
    id: '7',
    title: 'Online Multi-Table Tournaments',
    slug: 'online-multi-table-tournaments',
    instructor_name: 'Rampage Garrett',
    price: 99,
    level: 'Advanced',
    category: 'Tournaments',
    short_description: 'Dominate online poker tournaments with specialized strategies for virtual play.',
    full_description: 'Master the unique challenges and opportunities of online multi-table tournaments. Learn field dynamics, speed adjustments, and online-specific strategies.',
    thumbnail: '/courses/course-7.jpg',
  },
  {
    id: '8',
    title: 'Poker Hand Analysis Workshop',
    slug: 'poker-hand-analysis-workshop',
    instructor_name: 'GTO Wizard',
    price: 59,
    level: 'Beginner',
    category: 'Fundamentals',
    short_description: 'Deep dive into hand analysis and develop strong decision-making frameworks.',
    full_description: 'Learn how to analyze poker hands using GTO principles. Review real hands, understand decision points, and improve your intuition for correct plays.',
    thumbnail: '/courses/course-8.jpg',
  },
];

export const mockBlogs = [
  {
    id: '1',
    title: '10 Poker Mistakes Every Beginner Makes',
    slug: '10-poker-mistakes-beginners',
    author: 'Sarah Chen',
    content: 'Discover the most common mistakes that prevent beginners from becoming profitable poker players and how to avoid them.',
    excerpt: 'Learn from the mistakes thousands of poker beginners make and fast-track your journey to profitability.',
    published_at: new Date('2024-04-15'),
    category: 'Tips & Tricks',
    image: '/blog/blog-1.jpg',
  },
  {
    id: '2',
    title: 'The Mathematics of Pot Odds Explained',
    slug: 'mathematics-pot-odds',
    author: 'Michael Torres',
    content: 'A comprehensive guide to understanding pot odds, implied odds, and how to use them to make better decisions.',
    excerpt: 'Master the mathematical foundation that separates casual players from professionals.',
    published_at: new Date('2024-04-08'),
    category: 'Strategy',
    image: '/blog/blog-2.jpg',
  },
  {
    id: '3',
    title: 'Managing Tilt: A Mental Game Guide',
    slug: 'managing-tilt-mental-game',
    author: 'Jessica Roberts',
    content: 'Understand the psychological aspects of tilt and develop proven techniques to maintain emotional control during losing streaks.',
    excerpt: 'Tilt control is the difference between winning and losing players. Learn how to master it.',
    published_at: new Date('2024-03-28'),
    category: 'Psychology',
    image: '/blog/blog-3.jpg',
  },
  {
    id: '4',
    title: 'Live vs Online Poker: Key Differences',
    slug: 'live-vs-online-poker',
    author: 'James Williams',
    content: 'Explore the fundamental differences between live and online poker games and how to adapt your strategy for each format.',
    excerpt: 'Playing online? Or heading to the casino? Learn what changes when you switch formats.',
    published_at: new Date('2024-03-15'),
    category: 'Strategy',
    image: '/blog/blog-4.jpg',
  },
  {
    id: '5',
    title: 'Bankroll Growth: From $100 to $10,000',
    slug: 'bankroll-growth-100-to-10000',
    author: 'David Kumar',
    content: 'A real-world case study on building a bankroll from scratch and the decisions that led to 100x growth.',
    excerpt: 'See how disciplined bankroll management and solid strategy can grow a small stake into serious profits.',
    published_at: new Date('2024-03-01'),
    category: 'Bankroll',
    image: '/blog/blog-5.jpg',
  },
  {
    id: '6',
    title: 'Value Betting: The Profit Engine',
    slug: 'value-betting-profit-engine',
    author: 'Emma Johnson',
    content: 'Learn how professional players extract maximum value from their strong hands and grow their winnings consistently.',
    excerpt: 'Value betting is where the money comes from. Master this fundamental concept to increase your profits.',
    published_at: new Date('2024-02-20'),
    category: 'Strategy',
    image: '/blog/blog-6.jpg',
  },
];

export const mockCommunityTestimonials = [
  {
    name: 'Alex Rodriguez',
    role: 'Professional Cash Game Player',
    quote: 'The community here is incredible. The daily strategy discussions and hand reviews have improved my game so much.',
    avatar: '/avatars/avatar-1.jpg',
  },
  {
    name: 'Emma Thompson',
    role: 'Tournament Grinder',
    quote: 'Best poker community I\'ve found. Everyone is supportive and genuinely wants to help each other improve.',
    avatar: '/avatars/avatar-2.jpg',
  },
  {
    name: 'Marcus Johnson',
    role: 'Amateur Enthusiast',
    quote: 'Started as a casual player, now making consistent profits thanks to the coaching and support from the community.',
    avatar: '/avatars/avatar-3.jpg',
  },
  {
    name: 'Lisa Chen',
    role: 'High Roller Player',
    quote: 'The network opportunities alone are worth joining. I\'ve made some of my best poker friends here.',
    avatar: '/avatars/avatar-4.jpg',
  },
  {
    name: 'James Wilson',
    role: 'Poker Coach',
    quote: 'An amazing group of serious poker players dedicated to growth and improvement. Highly recommend joining!',
    avatar: '/avatars/avatar-5.jpg',
  },
];

export const mockCarouselBanners = [
  {
    id: 1,
    title: 'Master Poker Strategy',
    subtitle: 'Learn from world-class professionals and transform your game',
    image: '/banners/banner-1.jpg',
    cta: 'Explore Courses',
  },
  {
    id: 2,
    title: 'Texas Hold\'em Mastery',
    subtitle: 'Taught by Daniel Negreanu - Get the fundamentals right',
    image: '/courses/course-1.jpg',
    cta: 'Enroll Now',
    course: 'texas-holdem-mastery',
  },
  {
    id: 3,
    title: 'Advanced Tournament Strategy',
    subtitle: 'Learn from Phil Ivey\'s battle-tested tournament techniques',
    image: '/courses/course-2.jpg',
    cta: 'Start Learning',
    course: 'advanced-tournament-strategy',
  },
  {
    id: 4,
    title: 'Psychology of Winning',
    subtitle: 'Master the mental game with Jared Tendler',
    image: '/courses/course-5.jpg',
    cta: 'Join Course',
    course: 'psychology-winning-poker',
  },
  {
    id: 5,
    title: 'Position-Based Strategy',
    subtitle: 'Dominate from every seat with Vanessa Selbst',
    image: '/courses/course-4.jpg',
    cta: 'Learn Now',
    course: 'position-based-poker-strategy',
  },
];

export const categories = [
  'All Courses',
  'Cash Games',
  'Tournaments',
  'Fundamentals',
  'Live Poker',
  'Strategy',
];
